# Generated by Django 5.0.1 on 2025-02-05 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infrastructure", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="manual_urgency",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Overdue"),
                    (2, "Critical"),
                    (3, "High"),
                    (4, "Medium"),
                    (5, "Low"),
                ],
                help_text="Manual override for invoice urgency. If not set, urgency is calculated from due date.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total invoice amount. Maximum 99,999,999.99. Negative amounts not allowed.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(
                help_text="Date when payment is due. Used for overdue calculations and urgency levels."
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="file_path",
            field=models.CharField(
                help_text="Relative path to the stored invoice PDF file in the system.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(
                help_text="Unique identifier for the invoice. Can contain special characters and varies by country format.",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Payment"),
                    ("paid", "Payment Received"),
                    ("overdue", "Payment Overdue"),
                ],
                default="pending",
                help_text="Current payment status of the invoice. Automatically updated based on payment and due date.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="uploaded_by",
            field=models.ForeignKey(
                help_text="User who uploaded the invoice PDF. Protected from deletion.",
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
