# Generated by Django 5.0.1 on 2025-03-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infrastructure", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="company_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
