# Generated by Django 5.0.1 on 2025-02-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "infrastructure",
            "0002_alter_invoice_options_invoice_manual_urgency_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(
                help_text=(
                    "Business-specific identifier for the invoice. "
                    "Can contain special characters and varies by "
                    "country format. "
                    "Note: Invoice numbers may be similar or identical due to:"
                    "1) Different suppliers using the same numbering format "
                    "2) OCR extraction errors requiring manual correction "
                    "3) Initial automated extraction before user verification "
                    "4) Manual edits during the invoice review process. "
                    "Therefore, invoice numbers are not constrained to be "
                    "unique in the system."
                ),
                max_length=100,
            ),
        ),
    ]
