# Generated by Django 5.0.1 on 2025-03-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infrastructure", "0004_invoice_bic_invoice_buyer_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="file_size",
            field=models.BigIntegerField(
                blank=True, help_text="Size of the uploaded file in bytes.", null=True
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="file_type",
            field=models.CharField(
                blank=True,
                help_text="MIME type of the uploaded file.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="original_file_name",
            field=models.CharField(
                blank=True,
                help_text="Original name of the uploaded file.",
                max_length=255,
                null=True,
            ),
        ),
    ]
