name: Linting && Testing

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black==23.12.1 flake8==7.0.0

      - name: Run Black
        run: |
          cd backend
          black . --check --diff || (
            echo "::error::Black formatting check failed. Run 'black .' locally to fix."
            exit 1
          )

      - name: Run Flake8
        run: |
          cd backend
          flake8 .

  test:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start Docker Services
        run: |
          cd infrastructure
          docker compose up -d

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          cd backend
          pip install --upgrade pip
          pip install -r config/requirements/base.txt -r config/requirements/development.txt

      - name: Copy .env.example and inject Fernet key
        run: |
          cp backend/.env.example backend/.env
          key=$(python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())")
          sed -i "s/^FERNET_KEY=.*/FERNET_KEY=$key/" backend/.env

      - name: Run Migrations
        run: |
          cd backend
          python manage.py migrate

      - name: Run Tests
        run: |
          cd backend
          python manage.py test

      - name: Shutdown Docker
        if: always()
        run: |
          cd infrastructure
          docker compose down