name: Verify PR Source Branch

on:
  pull_request:
    branches:
      - main

jobs:
  verify-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Verify PR is from staging
        run: |
          SOURCE_BRANCH="${{ github.head_ref }}"
          TARGET_BRANCH="${{ github.base_ref }}"
          
          echo "Source branch: $SOURCE_BRANCH"
          echo "Target branch: $TARGET_BRANCH"
          
          if [ "$TARGET_BRANCH" == "main" ] && [ "$SOURCE_BRANCH" != "staging" ]; then
            echo "::error::Pull requests to main must come from the staging branch. Found source: $SOURCE_BRANCH"
            exit 1
          fi 